# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Mon Mar 21 10:11:37 2022
# ------------------------------------------------

package:
  name: cryptography
  version: 36.0.2
source:
  sha256: 70f8f4f7bb2ac9f340655cbac89d68c527af5bb4387522a8413e841e3e6628c9
  url: https://pypi.io/packages/source/c/cryptography/cryptography-36.0.2.tar.gz
build:
  number: '0'
  script:
    - export PYO3_CROSS_INCLUDE_DIR=$PREFIX/include
    - export PYO3_CROSS_LIB_DIR=$SP_DIR/../
    - export PYO3_CROSS_PYTHON_VERSION=$PY_VER
    - /Users/runner/miniforge3/conda-bld/cryptography_1647857630705/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
      -m pip install . -vv
  string: py39hbe5e4b8_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - cctools_osx-arm64 973.0.1 hef7e2f4_10
    - cffi 1.15.0 py39he338e87_0
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_8
    - clangxx 12.0.1 default_he082bbe_4
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - cross-python_osx-arm64 3.9 22_cpython
    - crossenv 1.2.0 pyhd8ed1ab_4
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 hc6b1d1e_10
    - ld64_osx-arm64 609 hf6d2360_10
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 13.0.1 hc203e6f_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.16 haf1e3a3_0
    - libllvm12 12.0.1 hd011deb_2
    - libllvm13 13.0.1 h64f94b2_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 he49afe7_0
    - openssl 3.0.0 h0d85af4_2
    - popt 1.16 h7b079dc_2002
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.9.10 hea1dfa3_2_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h652f650_3
    - rust 1.59.0 h7e1429e_0
    - rust-std-aarch64-apple-darwin 1.59.0 hf1a8007_0
    - rust-std-x86_64-apple-darwin 1.59.0 h059895a_0
    - rust_osx-arm64 1.59.0 h87c4a17_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.37.1 hb516253_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2022a h191b570_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.2 h582d3a0_0
  host:
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2021.10.8 h4653dfc_0
    - cffi 1.15.0 py39h52b1de0_0
    - libffi 3.4.2 h3422bc3_5
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.3 hc470f4d_0
    - openssl 1.1.1l h3422bc3_0
    - pip 22.0.4 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - python 3.9.10 hd16f9c5_2_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 hedafd6a_0
    - semantic_version 2.9.0 pyhd8ed1ab_0
    - setuptools 60.10.0 py39h2804cbe_0
    - setuptools-rust 1.1.2 pyhd8ed1ab_0
    - sqlite 3.37.1 h7e3ccbd_0
    - tk 8.6.12 he1e0b03_0
    - typing_extensions 4.1.1 pyha770c72_0
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 hee7b306_1013
  run:
    - cffi >=1.12
    - openssl >=1.1.1l,<1.1.2a
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0 *_cpython
    - python_abi 3.9.* *_cp39
test:
  commands:
    - pytest
  imports:
    - cryptography
    - cryptography.fernet
    - cryptography.hazmat
    - cryptography.hazmat.backends
    - cryptography.hazmat.backends.openssl
    - cryptography.hazmat.bindings
    - cryptography.hazmat.bindings.openssl
    - cryptography.hazmat.primitives
    - cryptography.hazmat.primitives.asymmetric
    - cryptography.hazmat.primitives.ciphers
    - cryptography.hazmat.primitives.kdf
    - cryptography.hazmat.primitives.twofactor
    - cryptography.x509
  requires:
    - cryptography-vectors 36.0.2.*
    - hypothesis
    - iso8601
    - pretend
    - pytest
    - pytest-subtests
    - pytz
  source_files:
    - tests
about:
  description: 'cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces

    to common cryptographic algorithms such as symmetric ciphers, message

    digests, and key derivation functions..

    '
  dev_url: https://github.com/pyca/cryptography
  doc_source_url: https://github.com/pyca/cryptography/blob/master/docs/index.rst
  doc_url: http://cryptography.readthedocs.io/
  home: cryptography.io
  license: Apache-2.0 AND BSD-3-Clause AND PSF-2.0 AND MIT
  license_family: BSD
  license_file: LICENSE
  summary: cryptography is a package designed to expose cryptographic primitives and
    recipes to Python developers.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - ocefpaf
