# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Mar 15 14:37:03 2022
# ------------------------------------------------

package:
  name: conda-package-handling
  version: 1.8.0
source:
  sha256: 0423c6dcb384e7ce369e72311cbd0ba9d57d52055f809bfc5b1c6602a05731b3
  url: https://github.com/conda/conda-package-handling/archive/1.8.0.tar.gz
build:
  entry_points:
    - cph = conda_package_handling.cli:main
  missing_dso_whitelist: null
  number: '0'
  script: /Users/runner/miniforge3/conda-bld/conda-package-handling_1647355403437/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: py39hb18efdd_0
requirements:
  build:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h609b070_9
    - cctools_osx-arm64 973.0.1 h7ef2fa9_9
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-arm64 12.0.1 h160513a_7
    - clangxx 12.0.1 default_he082bbe_4
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - cross-python_osx-arm64 3.9 21_cpython
    - crossenv 1.2.0 pyhd8ed1ab_4
    - cython 0.29.28 py39h9fcab8e_0
    - gettext 0.19.8.1 hd1a6beb_1008
    - ld64_osx-64 609 hc6b1d1e_9
    - ld64_osx-arm64 609 hf6d2360_9
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 13.0.1 hc203e6f_0
    - libffi 3.4.2 h0d85af4_5
    - libiconv 1.16 haf1e3a3_0
    - libllvm12 12.0.1 hd011deb_2
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 12.0.1 hd011deb_2
    - lz4-c 1.9.3 he49afe7_1
    - ncurses 6.3 he49afe7_0
    - openssl 3.0.0 h0d85af4_2
    - popt 1.16 h7b079dc_2002
    - python 3.9.10 hea1dfa3_2_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h05e3726_0
    - rsync 3.2.3 h652f650_3
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - sqlite 3.37.0 h23a322b_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.12 h5dbffcc_0
    - tzdata 2021e he74cb21_0
    - xxhash 0.8.0 h35c211d_3
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h9173be1_1013
    - zstd 1.5.2 h582d3a0_0
  host:
    - _libarchive_static_for_cph 3.3.3 h37bb66c_5
    - bzip2 1.0.8 h3422bc3_4
    - ca-certificates 2021.10.8 h4653dfc_0
    - cython 0.29.28 py39hfb83b0d_0
    - libcxx 13.0.1 h6a5c8ee_0
    - libffi 3.4.2 h3422bc3_5
    - libzlib 1.2.11 hee7b306_1013
    - ncurses 6.3 hc470f4d_0
    - openssl 3.0.0 h3422bc3_2
    - pip 22.0.4 pyhd8ed1ab_0
    - python 3.9.10 h38ef502_2_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 hedafd6a_0
    - setuptools 60.9.3 py39h2804cbe_0
    - sqlite 3.37.0 h72a2b83_0
    - tk 8.6.12 he1e0b03_0
    - tzdata 2021e he74cb21_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h642e427_1
    - zlib 1.2.11 hee7b306_1013
  run:
    - python >=3.9,<3.10.0a0
    - python >=3.9,<3.10.0a0 *_cpython
    - python_abi 3.9.* *_cp39
    - six
    - tqdm
test:
  commands:
    - pytest tests -k "not test_secure_refusal_to_extract_abs_paths"
  imports:
    - conda_package_handling
    - conda_package_handling.archive_utils_cy
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock
  source_files:
    - tests
about:
  home: https://github.com/conda/conda-package-handling
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - static_deps_licenses/bzip2.txt
    - static_deps_licenses/libarchive.txt
    - static_deps_licenses/libiconv.txt
    - static_deps_licenses/zlib.txt
    - static_deps_licenses/zstd.txt
  summary: Create and extract conda packages of various formats
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - dbast
    - msarahan
